ARG BASE_IMAGE=registry.redhat.io/ubi8/ubi
FROM ${BASE_IMAGE}
USER root
RUN dnf install -y rpm-build && mkdir -p /root/rpmbuild/SPECS && mkdir -p /root/rpmbuild/SOURCES
COPY onavim.spec /root/rpmbuild/SPECS
COPY onavim-*.tar.gz /root/rpmbuild/SOURCES
RUN rpmbuild -ba /root/rpmbuild/SPECS/onavim.spec
RUN find /root/rpmbuild/RPMS -path */onavim* -exec dnf install -y {} \;

RUN alternatives --set python3 /usr/bin/python3.11
RUN python3 -m ensurepip
RUN python3 -m pip install \
    --index-url https://pdnexus.profidata.com/repository/pypi-group/simple \
    --upgrade pip
RUN python3 -m pip install \
    --index-url https://pdnexus.profidata.com/repository/pypi-group/simple \
    "python-lsp-server[yapf]" pytest pexpect pytest-httpserver requests
COPY lsp.pylsp.vim /root

COPY pd.onavimrc /root/.onavimrc

RUN dnf install -y socat

ENTRYPOINT []
CMD ["/bin/bash", "-c", "/usr/sbin/sshd -p 53022 && exec bash -l"]
