ARG BASE_IMAGE=registry.redhat.io/ubi8/ubi
FROM ${BASE_IMAGE}
USER root
RUN dnf install -y rpm-build && mkdir -p rpmbuild/SPECS && mkdir -p rpmbuild/SOURCES
COPY . onavim
RUN cd onavim && ./rpm.sh
RUN find . -path rpmbuild/RPMS/*/onavim* -exec dnf install -y {}
