#! /usr/bin/env bash

rund=$(dirname $0)/run
mkdir -p "$rund"
. ~/.sh/logging.sh "$rund"

path=$1
width=$2
height=$3

function filteredLs {
    ls -pA1 $1 | grep -v -e ".swp$" -e "^Session.vim$"
}

function toNeedle {
    sed\
        -e "\\:^$1$: { s:.*:$2 $3 $4 \\:&:; q; }"\
        -e "s:.*:$2 $3 1 \\:&:"
}

function afterNeedle {
    sed -e "0,\\:^$1$: d" -e "s:.*:$2 $3 0 \\:&:"
}

function irRec {
    local dir=$1
    local levr="${2:-0}"
    local foll=$(($levr/5))
    local levl=$(($levr%5))
    local next;
    local selt;
    if read next; then
        [[ $next == */ ]] && selt=2 || selt=3
        filteredLs $dir | toNeedle $next $foll $levl $selt
        if [[ $selt == 2 ]]; then
            irRec "$dir/${next%/}" $(($levr + 1))
        fi
        filteredLs $dir | afterNeedle $next $foll $levl
    fi
}

function ir {
    echo $path | sed 's#/#/\n#g' | irRec '.'
}

function irWithHeightApplied {
    tmpf="$rund/$$.tmp"
    ir >"$tmpf"
    pat='/^[0-9] [0-9] 3/'
    coun="$pat { printf(\"%d \", NR) } END { print NR }"
    read line tota < <(awk "$coun" "$tmpf")
    context=$(($height/2))
    if [[ $line -le $context ]]; then
        cat $tmpf | head -n $height
    elif [[ $(($tota - $line)) -le $context ]]; then
        cat $tmpf | tail -n $height
    else
        f=$(($line - $context))
        t=$(($line + $context))
        cat $tmpf | sed -n -e "$f,$t p" -e "$((t + 1)) q"
    fi 
    rm $tmpf
}

sedi='\\:^[0-9] [0-9] [01] \\:" $1 "\$:'
seda='\\:^[0-9] [0-9] [23] \\:" $1 "\$:'
seda2='\\:^[0-9] [0-9] 2 \\:" $1 "\$:'
seda3='\\:^[0-9] [0-9] 3 \\:" $1 "\$:'

function sedAddIcons {
    si='{ s:.*:" $2 " &:;p;d; }'
    sa='{ s:.*:" $3 " &:;p;d; }'
    cat $(dirname $0)/ExplorerIcons.txt |\
        awk "{ printf \"$sedi $si\\n$seda $sa\\n\" }"
}

function addIcons {
    sed -f <(sedAddIcons)
}

function colorless {
    addIcons\
        | gawk -v w=$width -f $(dirname $0)/ExplorerColorless.awk
}

function sedGetColors {
    si='{ s:.*:\033[38;5;245m\\:" $4 ":;p;d; }'
    sa2='{ s:.*:\\:" $5 ":;p;d; }'
    sa3='{ s:.*:\033[48;5;237m\\:" $5 ":;p;d; }'
    cat $(dirname $0)/ExplorerIcons.txt |\
        awk "{ printf \"$sedi $si\\n$seda2 $sa2\\n$seda3 $sa3\\n\" }"
}

function getColors {
    sed -f <(sedGetColors)
}

function colorAnnotated {
    paste -d ":" <(getColors <"$1") <(colorless <"$1")
}

function applyColor {
    awk -F":" '{ gsub(/^>*[ ]*[│╰]? /, $1 "&" $2, $3); print $3 "\033[0m" $1 $4 "\033[0m" }'
}

irf="$rund/$$.ir.tmp"
irWithHeightApplied >"$irf"
colorAnnotated "$irf" | applyColor
rm "$irf"
