set runtimepath=$VIM,$VIMRUNTIME

source $VIMRUNTIME/defaults.vim

syntax enable

inoremap vv <Esc>
nnoremap <C-S> :w <CR>
nnoremap <C-H> <C-W>h
nnoremap <C-S-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-S-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-S-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-S-L> <C-W>l

nnoremap gf :vertical wincmd F <CR> <bar> :wincmd H <CR>

let mapleader = " "

map <Leader>v <C-V>
nnoremap <Leader><Backspace> :b # <CR>

nnoremap <Leader>h :call TerminalSensitiveWindowMove("H") <CR>
nnoremap <Leader>j :call TerminalSensitiveWindowMove("J") <CR>
nnoremap <Leader>k :call TerminalSensitiveWindowMove("K") <CR>
nnoremap <Leader>l :call TerminalSensitiveWindowMove("L") <CR>

nnoremap <Leader>o :OpFile <CR>
nnoremap <Leader>s :vsplit <bar> :OpFile <CR>
nnoremap <Leader>g :call OpGrepWithWordUnderCursor() <CR>
nnoremap <Leader>b :OpGitLog <CR>
nnoremap <Leader>d :let @d=expand('%:p').':'.line('.') <bar> let @f=expand('%:p') <bar> let @l=line('w0').','.line('w$') <CR>
nnoremap <Leader>r :OpSession <CR>
nnoremap <Leader>p :vsp <bar> :exe "lcd "..expand("%:h") <bar> :terminal ++curwin <CR>
nnoremap <Leader>n :LspGotoDefinition <CR>

nnoremap <C-P> :call ToggleCodeTerminal() <CR>
inoremap <C-P> <Esc> :call ToggleCodeTerminal() <CR>
tnoremap nn <C-W>: call ToggleCodeTerminal() <CR>
tnoremap vv <C-W>N

set tabstop=4
set shiftwidth=4 smarttab expandtab
set listchars=eol:¬,tab:»\ ,trail:~,extends:>,precedes:<,space:⸱
set fillchars=vert:│
set list
set display=uhex
highlight SpecialKey ctermfg=darkgrey
highlight NonText ctermfg=darkgrey
set number

let &t_Co=256
let g:gruvbox_contrast_dark="soft"

let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1

call plug#begin($VIM..'/plugged')
Plug 'junegunn/fzf'
Plug 'morhetz/gruvbox'
Plug 'easymotion/vim-easymotion'
Plug 'yegappan/lsp'
call plug#end()

silent! colorscheme gruvbox

set background=dark

hi! link StatusLine CursorLineNr
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
set laststatus=2
hi normal ctermfg=NONE ctermbg=NONE
hi VertSplit ctermbg=NONE ctermfg=237

map <expr> <Leader>f TerminalAwareEasymotionAction("bd-f2")
map <expr> <Leader>t TerminalAwareEasymotionAction("bd-t2")
map <expr> <Leader>w TerminalAwareEasymotionAction("bd-w")

set sessionoptions = "buffers"

set ignorecase
set smartcase
set hlsearch
hi! CurSearch ctermbg=226 ctermfg=black

let g:lspOpts = #{
            \    showDiagWithSign: v:false
            \  }
autocmd User LspSetup call LspOptionsSet(lspOpts)

let g:lspServers = [#{
            \    name: 'clang',
            \    filetype: ['h', 'c', 'cpp'],
            \    path: '/usr/bin/clangd',
            \    args: ['--background-index']
            \  }]
autocmd User LspSetup call LspAddServer(lspServers)
nnoremap <Leader>? :LspDiagCurrent <CR>
nnoremap =% :LspFormat <CR>
