set runtimepath=$VIM,$VIMRUNTIME

source $VIMRUNTIME/defaults.vim
set mouse=

syntax enable

inoremap vv <Esc>
nnoremap <Enter> i
nnoremap <C-S> :w <CR>
nnoremap <C-H> <C-W>h
nnoremap <C-S-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-S-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-S-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-S-L> <C-W>l

nnoremap gf :wincmd F <CR>

let mapleader = " "

map <Leader>v <C-V>
nnoremap <Leader><Backspace> :b # <CR>

nnoremap <Leader>h :call TerminalSensitiveWindowMove("H") <CR>
nnoremap <Leader>j :call TerminalSensitiveWindowMove("J") <CR>
nnoremap <Leader>k :call TerminalSensitiveWindowMove("K") <CR>
nnoremap <Leader>l :call TerminalSensitiveWindowMove("L") <CR>

nnoremap <Leader>o :OpFile <CR>
nnoremap <Leader>s :vsplit <bar> :OpFile <CR>
nnoremap <Leader>g :call OpGrepWithWordUnderCursor() <CR>
nnoremap <Leader>b :OpGitLog <CR>
nnoremap <Leader>d :let @d=expand('%:p').':'.line('.')<CR>:let @j='com.'.substitute(split(expand('%:r'), '/com/')[-1].':'.line('.'), '/', '.', 'g')<CR>
nnoremap <Leader>r :OpSession <CR>
nnoremap <Leader>p :call term_start("bash -i", { "cwd": expand("%:h"), "term_finish": "close" }) <CR>
nnoremap <Leader>n :LspGotoDefinition <CR>

nnoremap <Leader>; :call ToggleCodeTerminal() <CR>
inoremap <Leader>; <Esc> :call ToggleCodeTerminal() <CR>
tnoremap <Leader>; <C-W>: call ToggleCodeTerminal() <CR>
tnoremap vv <C-W>N

set tabstop=4
set shiftwidth=4 smarttab expandtab
set listchars=eol:¬,tab:»\ ,trail:~,extends:>,precedes:<,space:⸱
set fillchars=vert:│
set display=uhex
highlight SpecialKey ctermfg=darkgrey
highlight NonText ctermfg=darkgrey
set number

let &t_Co=256
let g:gruvbox_contrast_dark="soft"

let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1

call plug#begin($VIM..'/plugged')
Plug 'junegunn/fzf'
Plug 'morhetz/gruvbox'
Plug 'easymotion/vim-easymotion'
Plug 'yegappan/lsp'
Plug 'bfrg/vim-c-cpp-modern'
call plug#end()

silent! colorscheme gruvbox

set background=dark

hi! link StatusLine CursorLineNr
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
set laststatus=2
hi normal ctermfg=NONE ctermbg=NONE
hi VertSplit ctermbg=NONE ctermfg=237

map <expr> <Leader>f TerminalAwareEasymotionAction("bd-f2")
map <expr> <Leader>t TerminalAwareEasymotionAction("bd-t2")
map <expr> <Leader>w TerminalAwareEasymotionAction("bd-w")

set sessionoptions = "buffers"

set ignorecase
set smartcase
set hlsearch
hi! CurSearch ctermbg=226 ctermfg=black

let g:lspOpts = #{
            \    showDiagWithSign: v:false
            \  }
autocmd User LspSetup call LspOptionsSet(lspOpts)

let g:lspServers = [#{
            \    name: 'clang',
            \    filetype: ['h', 'c', 'cpp', 'objcpp'],
            \    path: '/usr/bin/clangd',
            \    args: ['--background-index']
            \  }]
autocmd User LspSetup call LspAddServer(lspServers)
nnoremap <Leader>? :LspDiagCurrent <CR>
nnoremap =% :LspFormat <CR>

autocmd BufEnter,BufFilePre *.metal set filetype=cpp
autocmd BufEnter,BufFilePre *.fbs set filetype=cpp
