#! /usr/bin/env bash

rund="$XDG_RUNTIME_DIR/onavim"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

tmuxSocket="/tmp/$$.code.tmux.socket"
trap "rm $tmuxSocket" EXIT
tmux -2 -S "$tmuxSocket" -f "$(dirname $0)/../etc/tmux.conf" new "$(dirname $0)/Code $tmuxSocket $*"
tmux -2 -S "$tmuxSocket" wait-for "$tmuxSocket"
