#! /usr/bin/env bash

sh=$(realpath $(dirname $0))

rund="$XDG_RUNTIME_DIR/onavim"
mkdir -p "$rund"
. $sh/logging.sh "$rund"

tmuxSocket="$1"
cd "$2"
sess="$3"

mkfifo "$rund/$$.fifo"

explorerWidth=25
minimapWidth=15
side=$(($explorerWidth + $minimapWidth))
bot=7

tmux -2 -S "$tmuxSocket" split-window -hdP -l $side -F "#{pane_index} #{pane_pid} #{pane_height}" "$sh/ExplorerServer" >"$rund/$$.fifo" &
read explorerPaneId explorerServerPid h <"$rund/$$.fifo"
explorerServerSocket="$rund/$explorerServerPid.socket"
explorerHeight=$(($h - $bot - 1))

tmux -2 -S "$tmuxSocket" split-window -d -t $explorerPaneId -l $bot \
    "$sh/Status $side $bot '$sess' '$tmuxSocket'"
tmux -2 -S "$tmuxSocket" pipe-pane -I -t {bottom-right} "echo 'sessions'"
tmux -2 -S "$tmuxSocket" bind-key -n C-e \
    pipe-pane -I -t {bottom-right} "echo 'explorer'" \\\; \
    select-pane -t {bottom-right}

tmux -2 -S "$tmuxSocket" split-window -hdPb -t $explorerPaneId -l $minimapWidth -F "#{pane_pid} #{pane_width} #{pane_height}" "$sh/MinimapServer" >"$rund/$$.fifo" &
read minimapServerPid minimapWidth minimapHeight <"$rund/$$.fifo"
minimapServerSocket="$rund/$minimapServerPid.socket"

opGrepServerSocket="$rund/$$.OpGrepServer.socket"
$sh/OpGrepServer "$opGrepServerSocket" &
opGrepServerPid=$!

function cleanup {
    kill $opGrepServerPid
    wait $opGrepServerPid
    rm "$rund/$$.fifo"
    tmux -2 -S "$tmuxSocket" kill-window
    tmux -2 -S "$tmuxSocket" wait-for -S "$tmuxSocket"
}
trap cleanup EXIT

sessionVim="$(dirname $sess)/vim-sessions/$(pwd | sed 's#/#ESCAPED_SLASH#g').vim"
[[ -e $sessionVim ]] && sessionOption="-S $sessionVim"

tmux -2 -S "$tmuxSocket" set -g prefix None
export PATH="$sh/restoretmuxbin:$PATH"

while ! [[ -e "$explorerServerSocket" ]]; do sleep 0.1s; done
while ! [[ -e "$minimapServerSocket" ]]; do sleep 0.1s; done
while ! [[ -e "$opGrepServerSocket" ]]; do sleep 0.1s; done

onavimDir=$(realpath "$sh/..")
export VIM="$onavimDir/etc/vim"
export VIMRUNTIME="$onavimDir/vim/vim91"
export VIMINIT=":"
export LANG=en_US.UTF-8
"$onavimDir/bin/vim" -i NONE $sessionOption \
    --cmd "let g:codeSessionsFile=\"$sess\""\
    --cmd "let g:codeCurrentSession=\"$(tail -n 1 $sess)\""\
    --cmd "let g:codeExplorerWidth=\"$explorerWidth\""\
    --cmd "let g:codeExplorerHeight=\"$explorerHeight\""\
    --cmd "let g:codeExplorerServerSocket=\"$explorerServerSocket\""\
    --cmd "let g:codeMinimapWidth=\"$minimapWidth\""\
    --cmd "let g:codeMinimapHeight=\"$minimapHeight\""\
    --cmd "let g:codeMinimapServerSocket=\"$minimapServerSocket\""\
    --cmd "let g:codeOpGrepServerSocket=\"$opGrepServerSocket\""

export PATH="${PATH#*:}
