#! /usr/bin/env bash

sh=$(realpath $(dirname $0))

rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $sh/logging.sh "$rund"

cd "$1"
sess="$2"

mkfifo "$rund/$$.fifo"

opGrepServerSocket="$rund/$$.OpGrepServer.socket"
$sh/OpGrepServer "$opGrepServerSocket" &
opGrepServerPid=$!

function cleanup {
    kill $opGrepServerPid
    wait $opGrepServerPid
    rm "$rund/$$.fifo"
}
trap cleanup EXIT

sessionVim="$(dirname $sess)/vim-sessions/$(pwd | gsed 's#/#ESCAPED_SLASH#g').vim"
settingsVim="$HOME/.onavimrc"
[[ -e $sessionVim ]] && sessionOption="-S $sessionVim"
[[ -e $settingsVim ]] && sessionOption="$sessionOption -S $settingsVim"

while ! [[ -e "$opGrepServerSocket" ]]; do sleep 0.1s; done

onavimDir=$(realpath "$sh/..")
export VIM="$onavimDir/etc/vim"
export VIMRUNTIME="$onavimDir/vim/vim91"
export VIMINIT=":"
"$onavimDir/bin/vim" -i NONE $sessionOption \
    --cmd "let g:codeSessionsFile=\"$sess\""\
    --cmd "let g:codeCurrentSession=\"$(tail -n 1 $sess)\""\
    --cmd "let g:codeOpGrepServerSocket=\"$opGrepServerSocket\""
