#! /usr/bin/env bash

rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

sed --version | grep -q GNU && export PATH="$(realpath $(dirname $0)/../gnu-alias):$PATH"
export LANG=en_US.UTF-8

$(dirname $0)/Code "$@"
