#! /usr/bin/env bash

gsed 's#^.*$#-o -regex &/[^/]*#' |
    xargs -J % find . -mindepth 1 \( -regex "./[^/]*" % \) -print -o -prune |
    gawk -v n="$1" '$0==n { ind=i+1 } { print $0; i++ } END { exit ind }'
