#! /usr/bin/env bash
        | gawk -v c=$(tput el) 'NR == 1 { printf("%s%s",$0,c) } NR > 1 { printf("\n%s%s",$0,c) }'

rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

path=$1
width=$2

sedi='\\:^[0-9] [0-9] [01] \\:" $1 "\$:'
seda='\\:^[0-9] [0-9] [23] \\:" $1 "\$:'
seda2='\\:^[0-9] [0-9] 2 \\:" $1 "\$:'
seda3='\\:^[0-9] [0-9] 3 \\:" $1 "\$:'

function sedAddIcons {
    si='{ s:.*:" $2 " &:;p;d; }'
    sa='{ s:.*:" $3 " &:;p;d; }'
    cat $(dirname $0)/ExplorerIcons.txt |\
        gawk "{ printf \"$sedi $si\\n$seda $sa\\n\" }"
}

function addIcons {
    gsed -f <(sedAddIcons)
}

function colorless {
    addIcons\
        | gawk -v w=$width -f $(dirname $0)/ExplorerColorless.awk
}

function sedGetColors {
    si='{ s:.*:\033[38;5;245m\\:" $4 ":;p;d; }'
    sa2='{ s:.*:\\:" $5 ":;p;d; }'
    sa3='{ s:.*:\033[48;5;237m\\:" $5 ":;p;d; }'
    cat $(dirname $0)/ExplorerIcons.txt |\
        gawk "{ printf \"$sedi $si\\n$seda2 $sa2\\n$seda3 $sa3\\n\" }"
}

function getColors {
    gsed -f <(sedGetColors)
}

function colorAnnotated {
    paste -d ":" <(getColors <"$1") <(colorless <"$1")
}

function applyColor {
    gawk -F":" '{ gsub(/^>*[ ]*[│╰]? /, $1 "&" $2, $3); print $3 "\033[0m" $1 $4 "\033[0m" }'
}

irf="$rund/$$.ir.tmp"
irWithHeightApplied >"$irf"
colorAnnotated "$irf" | applyColor
rm "$irf"
