#! /usr/bin/env bash
rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

socket=$rund/$$.socket
tmpf=$rund/$$.tmp
trap "rm $socket; rm $tmpf" EXIT

function init {
    width=$1
    height=$2
}

function heightAppliedTmpf {
    stats=$(tail -n 1 $tmpf)
    line=${states%:*}
    tota=${states#*.}
    context=$(($height/2))
    if [[ $line -le $context ]]; then
        gsed '$d' $tmpf | head -n $height
    elif [[ $(($tota - $line)) -le $context ]]; then
        gsed '$d' $tmpf | tail -n $height
    else
        first=$(($line - $context))
        last=$(($line + $context))
        gsed -n -e "$first,$last p" -e "$(($last + 1)) q" $tmpf
    fi
}

function previewWithPath {
    if [[ -z $height ]]; then
        return
    fi
    echo $1 |
        gsed 's#/#\n#g' |
        gawk 'BEGIN { l="." }{ l=l"/"$0; print l }' |
        $(dirname $0)/ExplorerList "$1" > $tmpf
    tput cup 0 0
    heightAppliedTmpf | $(dirname $0)/ExplorerRender $1 $width
    tput ed
}

function mainLoop {
    while read cmd args; do
        case $cmd in
            "init") init $args ;;
            "previewWithPath") previewWithPath $args ;;
            *) echo ExplorerServer does not recognize command $cmd ;;
        esac
    done
}

nc -kUl $socket | mainLoop
