#! /usr/bin/env bash
rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

socket=$rund/$$.socket
trap "rm $socket;" EXIT

function init {
    width=$1
    height=$2
}

function previewWithPath {
    if [[ -z $height ]]; then
        return
    fi
    tput cup 0 0
    echo $1 |
        gsed 's#/#\n#g' |
        gawk 'BEGIN { l="." }{ l=l"/"$0; print l }' |
        $(dirname $0)/ExplorerList "$1" $height |
        gawk -F: -v p="$1" -v w=$width -f $(dirname $0)/ExplorerRender.awk
    tput ed
}

function mainLoop {
    while read cmd args; do
        case $cmd in
            "init") init $args ;;
            "previewWithPath") previewWithPath $args ;;
            *) echo ExplorerServer does not recognize command $cmd ;;
        esac
    done
}

nc -kUl $socket | mainLoop
