#! /usr/bin/env bash
rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

socket=$rund/$$.socket
trap "rm $socket" EXIT

function init {
    width=$1
    height=$2
}

function previewWithPath {
    if [[ -z $height ]]; then
        return
    fi
    tput cup 0 0
    $(dirname $0)/Explorer $1 $width $height\
        | gawk -v c=$(tput el) 'NR == 1 { printf("%s%s",$0,c) } NR > 1 { printf("\n%s%s",$0,c) }'
    tput ed
}

function mainLoop {
    while read cmd args; do
        case $cmd in
            "init") init $args ;;
            "previewWithPath") previewWithPath $args ;;
            *) echo ExplorerServer does not recognize command $cmd ;;
        esac
    done
}

nc -kUl $socket | mainLoop
