#! /usr/bin/env bash

rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

socket=$1
function request {
    echo "init 20 30"
    echo "setPath MinimapServer"
    sleep 1
    echo "previewWithRange 12 40" && sleep 1
    echo "previewWithRange 50 60" && sleep 1
    echo "previewWithRange 1 90" && sleep 1
    echo "previewWithRange 20 40" && sleep 1
    echo "previewWithRange 5 15" && sleep 1
}
request | nc -U "$socket" || (echo "failed to connect"; exit)
