#! /usr/bin/env bash
rund=$(dirname $0)/run
mkdir -p $rund
. $(dirname $0)/logging.sh "$rund"

socket="${1:-$rund/$$.socket}"
infifo="$rund/$$.in.fifo"
outfifo="$rund/$$.out.fifo"
mkfifo "$infifo"
mkfifo "$outfifo"
trap "rm $infifo; rm $outfifo; rm $socket" EXIT

function reinit {
    previewArgs="$*"
    file=$1
    cont=$(($2-2))
    agas="${@:3}"
    maxi=$(ag "${agas[@]}" $file | wc -l)
    curi=0
}

function next {
    curi=$(($curi % $maxi + 1))
    rang="rmin = \$1 - $cont/2; rmax = \$1 + $cont/2; if (rmin < 1) { rmax -= (rmin - 1); rmin = 1; }  printf \"-r %d:%d -H %d\", rmin, rmax, \$1"
    bata=$(ag --numbers "${agas[@]}" $file | awk -F: "FNR == $curi { $rang }")
    echo "$bata"
}

function preview {
    [[ "$previewArgs" != "$*" ]] && reinit "$@"
    next
}

function get {
    line=$(ag --numbers "${agas[@]}" $file | awk -F: "FNR == $curi { print \$1 }")
    echo $line
}

function mainLoop {
    while true; do
        read cmd args
        case $cmd in
            "preview") preview $args >&$ifd ;;
            "get") get >&$ifd ;;
            "shutdown") echo "OK" >&$ifd; break ;;
            *) echo OpGrepServer does not recognize command $cmd >&$ifd ;;
        esac
    done
}

nc -kUl $socket <"$infifo" >"$outfifo" &
ncpid=$!
exec {ifd}>"$infifo"
mainLoop <"$outfifo"
kill $ncpid
