#! /usr/bin/env bash
rund="$XDG_RUNTIME_DIR/onavim"
mkdir -p $rund
. $(dirname $0)/logging.sh "$rund"

fifo="$rund/$$.fifo"
mkfifo $fifo
trap "rm $fifo" EXIT

socket=$1
shift

exec {requestOut}>&1

function askAndEcho {
    echo "$@"
    read response <$fifo
    echo "$response" >&$requestOut
}

askAndEcho "$@" | nc -U $socket >$fifo
