#! /usr/bin/env bash

rund=$(realpath $(dirname $0))/run
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

width=$1
height=$2
sess="$3"
tmuxSocket="$4"

cmd=""
while [[ -n $cmd ]] || read cmd; do
    tput clear
    case $cmd in
        sessions)
            $(dirname $0)/SessionList "$sess" $width $height
            cmd=""
            ;;
        explorer)
            fzf | xargs -I{} tmux -2 -S "$tmuxSocket" send-keys -t 0 ":e {}" Enter
            cmd="sessions"
            tmux -2 -S "$tmuxSocket" select-pane -t 0
            ;;
        *) echo "Unknown command: $cmd"; cmd="" ;;
    esac
done
