#! /usr/bin/env bash

rund="$HOME/.onavim.run"
mkdir -p "$rund"
. $(dirname $0)/logging.sh "$rund"

file="$1"
line="$2"

cp "$file" "$file.last"
cat "$file.last" | grep -v "^$line\$" > "$file"
echo "$line" >> "$file"
rm "$file.last"
