#! /usr/bin/env bash

rund=$(dirname $0)/run
mkdir -p "$rund"
. ~/.sh/logging.sh "$rund"

sessionLocation="$1"
[[ -z "$sessionLocation" && -e "$rund/sessions" ]] && sessionLocation=$(tail -n 1 "$rund/sessions")
[[ -z "$sessionLocation" ]] && sessionLocation=$(pwd)

function launch {
    remote="${1%:*}"
    if [[ "$remote" != "$1" ]]; then
        me=$(hostname -f)
        folder=$(ssh "$remote" "realpath '${1#*:}'")
        sesl="$remote:$folder"
        ~/.sh/WriteLeastRecentlyUsed "$rund/sessions" "$sesl"
        rdir="bin/run/sessions-from/$me"
        rdir=$(ssh "$remote" "mkdir -p '$rdir' && realpath '$rdir'")
        sess="$rdir/sessions"
        scp "$rund/sessions" "$remote:$sess"
        ssh -t "$remote" "chezmoi update && ~/.sh/CodeMain '$folder' '$sess'"
        scp "$remote:$sess" "$rund/sessions"
    else
        sesl="$(realpath $1)"
        ~/.sh/WriteLeastRecentlyUsed "$rund/sessions" "$sesl"
        ~/.sh/CodeMain "$sesl" "$rund/sessions"
    fi
    next=$(tail -n 1 "$rund/sessions")
    [[ "$next" == "$sesl" ]] && return
    launch "$next"
}

launch "$sessionLocation"
